### ISSUE TITLE
Members tag of the ListOfMembers struct typo

### ISSUE THREAD

**Issue by lifenod** [hanzo-io/gochimp3#5]
The tag should be `members` in https://github.com/hanzo-io/gochimp3/blob/408934c2f7c10ed14acac75d78aca8e2eff95e7d/members.go#L23

MailChimp API doc: https://developer.mailchimp.com/documentation/mailchimp/reference/lists/members/#read-get_lists_list_id_members

**Comment by zeekay** [comment]
Thanks! Fixed in master.
